dailyfresh_06/apps/cart/urls.py
import haystack
from django.conf.urls import include, url
from django.contrib import admin

from cart import views

urlpatterns = [
    url(r'^add$', views.AddCartView.as_view(),name='add'), #添加购物车
    url(r'^$', views.CartInfoView.as_view(),name='info'), #购物车详情页
    url(r'^update$', views.UpdateCartView.as_view(),name='update'), #更新购物车
    url(r'^delete$', views.DeleteCartView.as_view(),name='delete'), #删除购物车
]

dailyfresh_06/apps/goods/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<category_id>\d+)/(?P<page>\d+)$', views.ListView.as_view(), name='list'),

]

dailyfresh_06/apps/orders/urls.py
import haystack
from django.conf.urls import include, url
from django.contrib import admin

from orders import views

urlpatterns = [
    url(r'^place$', views.PlaceOrdereView.as_view(),name='place'),
]

dailyfresh_06/apps/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from users import views





urlpatterns = [
    url(r'^register$', views.RegisterView.as_view() ,name='register'),#注册
    url(r'^active/(?P<token>.+)$', views.ActiveView.as_view() ,name='active'),#激活
    url(r'^login$', views.LoginView.as_view() ,name='login'),#登录
    url(r'^logout$', views.LogoutView.as_view() ,name='logout'),#登出

    # 直接作为方法使用 装饰器  把视图函数传进来
    # url(r'^address$', login_required(views.AddressView.as_view()) ,name='address'),#收货地址
    url(r'^address$', views.AddressView.as_view() ,name='address'),#收货地址
    url(r'^info$', views.UserInfoView.as_view() ,name='info'),#用户信息
]

dailyfresh_06/dailyfresh_06/urls.py
import haystack
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    # 富文本应用
    url(r'^tinymce/', include('tinymce.urls')),
    # 搜索引擎 用来搜索的url
    url(r'^search/', include('haystack.urls')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]

dailyfresh_06/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh_06/apps/cart/views.py
import json

from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import View

# 添加购物车
from django_redis import get_redis_connection

from goods.models import GoodsSKU


# 如果没有登录 也可以添加购物车
# 登录后 把之前的购物车的数据 添加到登录的账户里

# 登录后   cart_userid: {'skuid1':10,'skuid2':3 ....}

# 没登录  cart: '{'skuid1':10,'skuid2':3 ....}' json
# 存到cookie  在登录后 把数据转到服务器redis存到当前用户下

class AddCartView(View):
    def post(self, request):

        # 用户信息user
        # 应该接收的数据 skuid  数量count

        # 接收传来数据方法里的参数
        user = request.user

        # 需求后来让产品改了 不登录也能添加
        # if not user.is_authenticated():  # 必须登录后才能添加
        #
        #     return JsonResponse({'code': 5, 'msg': '用户没登录'})
        # 商品的skuid

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 对数据校验(比如这个数据为空, 和这个数据乱传的清况, 通过判断和捕获异常的形式)
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'msg': '参数不全'})

        # 验证商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'msg': '商品不存在'})

        try:
            # 验证数量
            count = int(count)
        except Exception:
            return JsonResponse({'code': 3, 'msg': '数量不对'})

        # 数量不能超过库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'msg': '库存不足'})
        print(11111)
        # 如果用户登录 存到redis
        if user.is_authenticated():
            # 把数据存到redis   cart_userid: {'skuid1':10,'skuid2':3 ....}


            # 获取redis的链接实例
            # {b'skuid1': b'10', b'skuid2': b'3'....}
            redis_conn = get_redis_connection('default')
            # 判断当前的商品 是否已经存在于redis里

            # 获取商品之前的数量
            origin_count = redis_conn.hget('cart_%s' % user.id, sku_id)
            if origin_count is not None:
                # 已经存在 最后保存的数量 = 之前的数量+当前的数量
                # 注意redis里是string 要强转
                count += int(origin_count)
            # else:
            #     # 不存在   最后保存的数量 = 当前的数量
            # 保存到数据库
            redis_conn.hset('cart_%s' % user.id, sku_id, count)
        else:
            #  用户未登录 存到cookie中
            print(33)
            # 获取商品之前的数量
            # cart  ：  '{'skuid1':10,' skuid2':3 ....}'
            # 如果用户之前就没操作过购物车 获取的就是None
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                # 把字符串转为字典
                cart_dict = json.loads(cart_json)
            else:
                # 如果之前没操作过购物车 就生成一个空字典 方便后面使用
                cart_dict = {}
            print(sku_id)
            print(cart_dict)
            # 判断当前商品是否保存过
            if sku_id in cart_dict:
                print(3333)
                # 获取商品之前的数量
                origin_count = cart_dict.get(sku_id)
                count += origin_count

            # cart_dict :{'skuid1':10,' skuid2':3 ....}
            # 把添加后的数量 存到字典里
            print(222)
            cart_dict[sku_id] = count

        cart_num = 0
        # 如果登录 从redis查询购物车的数量
        if user.is_authenticated():
            # 查询购物车的数量
            # 获取用户
            user = request.user
            # 从redis中获取购物车信息
            redis_conn = get_redis_connection("default")
            # 如果redis中不存在，会返回None
            cart_dict = redis_conn.hgetall("cart_%s" % user.id)
            # else:
            # {'skuid1': 10, 'skuid2': 3....}
            # 没有登录 从cookie里获取  但是 获取的是旧的数据 新的数据已经在cart_dict里了
            # cart_json = request.COOKIES.get('cart')
            # cart_dict = json.loads(cart_json)
        print(3333)
        # 循环获取总的数量
        for val in cart_dict.values():
            cart_num += int(val)
        print(444)
        response = JsonResponse({'code': 0, 'msg': '添加购物车成功', 'cart_num': cart_num})
        print(555)
        print(cart_dict)
        if not user.is_authenticated():
            # 未登录 保存到cookie
            #  把字典转为字符串
            cart_json = json.dumps(cart_dict)
            # 保存到cookie中
            response.set_cookie('cart', cart_json)
        print(666)
        # {'code':3,'msg':'添加购物车失败'}   code 0 ：添加成功  代表状态码 一般0是成功
        return response


# 购物车信息页面
class CartInfoView(View):
    # 登录　在redis查数据
    # 没登录　cookie里查数据
    def get(self, request):
        user = request.user
        # 商品sku对象
        # 单个商品的数量
        # 单个商品的总价
        # 全部商品的数量
        # 全部商品的总价

        if user.is_authenticated():
            # 登录　在redis查数据
            redis_conn = get_redis_connection('default')
            # 获取所有的数据  {b'skuid1'：b'5', b'skuid2':b'10' }
            cart_dict = redis_conn.hgetall('cart_%s' % user.id)
        else:
            # 没登录　cookie里查数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}
            pass

        total_count = 0  # 全部商品的数量
        total_amount = 0  # 全部商品的总价
        skus = []  # 存放所有的sku对象
        # 遍历字典获取skuid 和数量
        for sku_id, count in cart_dict.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                # 不管当前异常 继续获取下面的数据
                continue
            # 强转为数字 因为reids里存的是字符串
            count = int(count)  # 单个商品的数量
            amount = sku.price * count  # 单个商品的总价
            # 把商品的数量和总价 存到当前商品对象里
            sku.count = count
            sku.amount = amount
            total_count += count  # 全部商品的数量
            total_amount += amount  # 全部商品的总价
            skus.append(sku)  # 所有的sku对象

            # 对数据校验

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }

        return render(request, 'cart.html', context)


class UpdateCartView(View):
    def post(self, request):
        user = request.user
        # 更新的是哪个sku  skuid
        # 更新成多少数量 count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 对数据校验
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'msg': '参数不完整'})

        try:
            # 判断商品是否存在
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'msg': '商品不存在'})

        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code': 3, 'msg': '数量不正常'})

        # 判断是否超过库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'msg': '库存不足'})

        # 判断是否登录  来决定更改redis还是cookie的数据
        if user.is_authenticated():
            # 更改redis  {'id':10,'id2':30}
            redis_conn = get_redis_connection('default')
            # 更改sku_id商品的数量为新的数量count
            redis_conn.hset('cart_%s' % user.id, sku_id, count)
            return JsonResponse({'code': 0, 'msg': '更新购物车数量成功'})
        else:
            # 更改cookie
            # 取出所有的数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}
            # 把商品数据更新数量
            cart_dict[sku_id] = count

            response = JsonResponse({'code': 0, 'msg': '更新购物车数量成功'})
            # 注意存cookie 要把字典转换回json字符串
            response.set_cookie('cart', json.dumps(cart_dict))
            return response


class DeleteCartView(View):
    def post(self, request):
        user = request.user
        # 商品sku_id
        sku_id = request.POST.get('sku_id')

        # 校验
        if not sku_id:
            return JsonResponse({'code': 1, 'msg': '参数不对'})

        if user.is_authenticated():
            # {'id': 10, 'id2': 30}
            # 如果登录 从redis删除数据
            redis_conn = get_redis_connection('default')
            # 删除一个属性对应的数据
            redis_conn.hdel('cart_%s' % user.id, sku_id)
            return JsonResponse({'code': 0, 'msg': '删除成功'})
        else:
            # 没登录 从cookie删除数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                # 不是空的才能去删除
                cart_dict = json.loads(cart_json)
                # 如果id在字典里 就删除
                if sku_id in cart_dict:
                    del cart_dict[sku_id]
                    response = JsonResponse({'code': 0, 'msg': '删除成功'})
                    # 注意存cookie 要把字典转回json字符串
                    response.set_cookie('cart', json.dumps(cart_dict))
                    return response

        return JsonResponse({'code': 0, 'msg': '删除成功'})

dailyfresh_06/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="#">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

dailyfresh_06/templates/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        <li><a href="#" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>
        <a href="#">新鲜水果</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.title }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unit }}g</span>
            </div>

            <div>
                {#            其它规格的sku#}

                {% for sku in other_skus %}
                    <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                {% endfor %}

            </div>
            <form action="{% url 'orders:place' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="sku_ids" value="{{ sku.id }}">
                <div class="goods_num clearfix">
                    <div class="num_name fl">数 量：</div>
                    <div class="num_add fl">
                        <input type="text" name="count" class="num_show fl" value="1">
                        <a href="javascript:;" class="add fr">+</a>
                        <a href="javascript:;" class="minus fr">-</a>
                    </div>
                </div>
                <div class="total">总价：<em>16.80元</em></div>
                <div class="operate_btn">
                    <input type="submit" class="buy_btn" value="立即购买">
                    <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
                </div>
            </form>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                        <li>
                            {#                           http://127.0.0.1:8000/goods/detail/2#}
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>
                        {#                        注意详情是html代码  转义的问题#}
                        {{ sku.goods.desc|safe }}
                    </dd>
                </dl>
            </div>

        </div>
    </div>
    {% csrf_token %}

    <div class="add_jump"></div>
{% endblock body %}


{% block bottom_files %}
    <script type="text/javascript">
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})

        $('#add_cart').click(function () {
            //向服务器上传的数据  skuid  和 count
            var data = {
                sku_id:{{ sku.id }},
                count: $('.num_show').val(), //数量
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }

            //添加购物车点击事件
            $.ajax({
                url: '/cart/add',
                type: 'post',
                data: data,
                dataType: 'json'
            }).done(function (data) {
                {#                {'code':0,'msg':'添加购物车成功','cart_num':cart_num}#}
                var code = data.code;
                var msg = data.msg;
                // code == 0时才有传data.cart_num
                if (code == 0) {
                    {#                    alert(msg)#}
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                //显示最后的数量
                                $('#show_count').html(data.cart_num);
                            });

                        });
                } else if (code == 5) {
                    //没登录 跳到登录页
                    location.href = '/users/login'
                } else {
                    alert(msg)
                }
            }).fail(function () {
                alert('网络异常')
            })
        })

        //购物车的加减号代码(不要求写就是一些前端的效果)
        $(".add").click(function () {
            //获取当前数量
            var num_show = $(".num_show").val();
            //转为int
            num_show = parseInt(num_show)
            //数量+1
            num_show += 1;
            //展示添加后的数量
            $(".num_show").val(num_show);
            //获取当前的单价
            var price = $(".show_pirze>em").html()
            price = parseFloat(price);
            //计算总价
            var total = price * num_show;
            //显示总价 保留两位小数
            $(".total>em").html(total.toFixed(2));
        });
        $(".minus").click(function () {
            var num_show = $(".num_show").val();
            num_show = parseInt(num_show)
            num_show -= 1;
            if (num_show < 1) {
                num_show = 1;
            }
            $(".num_show").val(num_show);
            var price = $(".show_pirze>em").html()
            price = parseFloat(price);
            var total = price * num_show;
            $(".total>em").html(total.toFixed(2));
        });


    </script>
{% endblock bottom_files %}

dailyfresh_06/templates/list.html
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        {#                        http://127.0.0.1:8000/goods/list/category.id/1#}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>
        <a href="">{{ category.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}

                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                {#                 http://127.0.0.1:8000/goods/list/category.id/1   ?sort=default#}
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in skus_page %}

                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

            </ul>

            <div class="pagenation">
                {% if skus_page.has_previous %}
{#                    skus_page.previous_page_number是获取上一页的页码#}
                    <a href="{% url 'goods:list' category.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pagenum in page_list %}
                    <a href="{% url 'goods:list' category.id pagenum %}?sort={{ sort }}" {% if pagenum == skus_page.number %}class="active"{% endif %}>{{ pagenum }}</a>
                {% endfor %}

                {% if skus_page.has_next %}
{#                    skus_page.next_page_number是获取下一页的页码#}
                    <a href="{% url 'goods:list' category.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}

dailyfresh_06/templates/static_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="#">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

dailyfresh_06/templates/user_center_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
            <form method="get" action="/search/">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock %}